#!/usr/bin/env bash

declare -a files_list

files_list=(
    "01-Foo.# .baR #. .ï.. bAz.txt"
    "02-Foo.@ .baR @. ..î. bAz.txt"
    "03-Foo.& .baR &. .é.è. bAz.txt"
    "04-Foo."". baR"". .à.ä.bAz.txt"
    "05-Foo.' .baR '. .ä.. bAz.txt"
    "06-Foo.( .baR (. .ù.û. bAz.txt"
    "07-Foo.{ .baR {. ..ä. bAz.txt"
    "08-Foo.[ .baR [. ... bAz.txt"
    "09-Foo.§ .baR §. ... bAz.txt"
    "10-Foo.è .baR è. ... bAz.txt"
    "11-Foo.! .baR !. .ä.. bAz.txt"
    "12-Foo.@ .baR ç. ï.î.ï.î bAz.txt"
    "13-Foo.@ .baR à. .€.€. bAz.txt"
    "14-Foo.) .baR ). .é é é é é .ä. bAz.txt"
    "15-Foo.} .baR }. .è è è è è .. bAz.txt"
    "16-Foo.] .baR ]. .ê ê ê ê ê .. bAz.txt"
    "17-Foo._ .baR _. .à à à à à .. bAz.txt"
    "18-Foo.- .baR -. .œ œ œ œ œ .. bAz.txt"
    "19-Foo.¨ .baR ¨. .ù ù ù ù ù .. bAz.txt"
    "20-Foo.^ .baR ^. .ç ç ç ç ç .. bAz.txt"
    "21-Foo.* .baR *. ... bAz.txt"
    "22-Foo.$ .baR $. ... bAz.txt"
    "23-Foo € baR € . bAz.txt"
    "24-Foo % baR %  bAz.txt"
    "25-Foo ù baR ù  bAz.txt"
    "26-Foo £ baR £  bAz.txt"
    "27-Foo \`\` baR \`\`  bAz.txt"
    "28-Foo < baR <  bAz.txt"
    "29-Foo > baR >  bAz.txt"
    "30-Foo ? baR ?  bAz.txt"
    "31-Foo , baR ,  bAz.txt"
    "32-Foo . baR .  bAz.txt"
    "33-Foo ; baR ;  bAz.txt"
    "34-Foo 1234 baR 56789 bAz.txt"
    "35-Foo \ baR \  bAz.txt"
    ".36-.Foo | baR . | . bAz.txt"
    ".37-.Foo : baR . : . bAz.txt"
    ".38-.Foo + baR . + . bAz.txt"
    ".39-.Foo = baR . = . bAz.txt"
    ".40-.Foo é baR . é . bAz.txt"
    ".41-.Foo è baR . è . bAz.txt"
    ".42-.Foo ê baR . ê . bAz.txt"
    ".43-.Foo à baR . à . bAz.txt"
    ".44-.Foo œ baR . œ . bAz.txt"
    ".45-.Foo ù baR . ù . bAz.txt"
    ".46-.Foo ç baR . ç . bAz.txt"
)
